import {
  LayoutDashboard,
  GraduationCap,
  Briefcase,
  Users,
  BookOpen,
  CircleDollarSign,
  BarChart3,
  LogOut,
  Pencil,
  Trash2,
  Plus,
  X,
  Check,
  Loader2,
  Settings,
  FileDown,
  Megaphone,
  DatabaseBackup,
  RotateCcw,
  Printer,
  Sun,
  Moon,
  CheckCircle2,
  Calendar,
  Circle,
  Search,
  Download,
  Heart,
  Copy,
  ChevronLeft,
  ChevronRight,
  Menu,
  Key,
  User,
  Lock,
  Cloud,
  Building,
  History
} from 'lucide-react';

export const ROUTES = {
  LANDING: '/',
  GUIDE: '/huong-dan',
  DASHBOARD: '/dashboard',
  STUDENTS: '/students',
  STUDENT_DETAIL: '/student/:id',
  TEACHERS: '/teachers',
  TEACHER_DETAIL: '/teacher/:id',
  STAFF: '/staff',
  CLASSES: '/classes',
  CLASS_DETAIL: '/class/:id',
  ATTENDANCE_DETAIL: '/attendance/:classId/:date',
  ATTENDANCE_HUB: '/attendance-hub',
  LOGIN: '/login',
  FINANCE: '/finance',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  ANNOUNCEMENTS: '/announcements',
  ROOMS: '/rooms',
  AUDIT_LOG: '/audit-log',
  PARENT_DASHBOARD: '/portal/dashboard',
  PARENT_REPORTS: '/portal/reports',
  PARENT_FINANCE: '/portal/finance',
  PARENT_ATTENDANCE: '/portal/attendance',
  TEACHER_CALENDAR: '/teacher-calendar',
};

export const ICONS = {
    dashboard: <LayoutDashboard size={24} />,
    students: <GraduationCap size={24} />,
    teachers: <Briefcase size={24} />,
    staff: <Users size={24} />,
    classes: <BookOpen size={24} />,
    finance: <CircleDollarSign size={24} />,
    reports: <BarChart3 size={24} />,
    logout: <LogOut size={24} />,
    edit: <Pencil size={20} />,
    delete: <Trash2 size={20} />,
    plus: <Plus size={24} />,
    close: <X size={24} />,
    check: <Check size={24} />,
    loading: <Loader2 size={24} className="animate-spin" />,
    settings: <Settings size={24} />,
    export: <FileDown size={24} />,
    announcement: <Megaphone size={24} />,
    backup: <DatabaseBackup size={24} />,
    restore: <RotateCcw size={24} />,
    print: <Printer size={24} />,
    sun: <Sun size={24} />,
    moon: <Moon size={24} />,
    checkCircle: <CheckCircle2 size={24} />,
    calendar: <Calendar size={24} />,
    circle: <Circle size={24} />,
    search: <Search size={20} />,
    download: <Download size={20} />,
    heart: <Heart size={24} />,
    copy: <Copy size={20} />,
    chevronLeft: <ChevronLeft size={24} />,
    chevronRight: <ChevronRight size={24} />,
    menu: <Menu size={24} />,
    key: <Key size={24} />,
    user: <User size={24} />,
    lock: <Lock size={24} />,
    drive: <Cloud size={24} />,
    rooms: <Building size={24} />,
    history: <History size={24} />,
};